name: Microservices CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Build and Test Calc Service (Unit)
        run: |
          docker build -t calc-test -f ./src/calc/Dockerfile_test ./src/calc
          docker run -d --name calc-test -p 5000:5000 calc-test
          sleep 15  # Wait for service to be ready
          newman run tests/calc_ut.postman_collection.json
          docker stop calc-test
      - name: Build and Test String Service
        run: |
          docker build -t string-test -f ./src/string/Dockerfile_test ./src/string
          docker run -d --name string-test -p 5001:5000 string-test
          sleep 15
          newman run tests/string_ut.postman_collection.json
          docker stop string-test
  
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build the Entire Architecture
        run: docker-compose build

      - name: Start All Services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run Integration Tests
        run: newman run tests/integration.postman_collection.json

      - name: Stop All Services
        run: docker-compose down
